.init-deploy:
  script:
    - touch .env
    - echo "Lufth_client_secret=$Lufth_client_secret" >> .env
    - echo "Lufth_client_id=$Lufth_client_id" >> .env
    - echo "Lufth_grant_type=$Lufth_grant_type" >> .env
    - echo "EXTRACTED_PATH=$EXTRACTED_PATH" >> .env
    - echo "ARCHIVES_PATH=$ARCHIVES_PATH" >> .env
    - mkdir -p ./airflow/logs
    - chmod -R 777 ./airflow/
    - docker compose down --remove-orphans
    - docker compose up -d --build

stages:
  - build
  - deploy-test
  - deploy-prod

deploy_to_test:
  stage: deploy-test
  tags:
    - runner-test
  environment:
      name: serveur-test
  script:
  - !reference [.init-deploy, script]
  only:
    - test_server

deploy_to_prod:
  stage: deploy-prod
  tags:
    - runner-prod
  environment:
      name: serveur-prod
  script:
    - !reference [.init-deploy, script]
  when: manual
  only:
    - main
